### ISSUE TITLE
docs.mun-lang.org is not accessible

### ISSUE THREAD

**Issue by iredmail** [mun-lang/website#54] opened 2020-10-10 00:20 UTC
When visiting https://docs.mun-lang.org, i got this:

```
Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

 Back to our site

If this is your site, and you weren't expecting a 404 for this path, please visit Netlify's "page not found" support guide for troubleshooting tips.
```

**Comment by baszalmstra** [comment] 2020-10-10 09:45
Thanks for reporting! 

This is a duplicate of https://github.com/mun-lang/mun/issues/277 so Im closing this in favor of the other issue.

**Closed by baszalmstra** 2020-10-10 09:45 UTC
